### PR TITLE
Refactor scraping method to improve efficiency and accuracy

### PR DESCRIPTION
**Pull request by kotaroyamazaki**
The previous implementation had a notable bottleneck in processing time, primarily due to the inefficient handling of page navigation and element selection. The enhancements in this PR are aimed at resolving these issues and optimizing the overall efficiency of the scraping process.

## Key Changes:
- Efficient Link Collection: The new logic first compiles a list of potential product links that match our specified item names, reducing the need for repetitive page navigation.
- Disabling Image Loading: Implemented args=["--no-images"] to prevent image loading during page navigation. This change significantly reduces data bandwidth usage and speeds up page loading times, directly impacting the overall scraping speed.
- Skipping Sold-Out or Hidden Items: Added a check if element.get_attribute("data-available") == "false" to skip over items that are marked as sold out or are hidden. This refinement ensures that the script focuses only on available items, thereby improving the efficiency of the scraping process.

## Impact:
- Performance: The refactoring has substantially reduced the processing time, addressing the previous bottleneck.
In my environment, when scraping two items, the processing time increased by approximately **2.5** times.

### Note:
I conducted this in the context of the Japanese shop environment. It would be appreciated if you could verify whether this process works correctly in other environments as well.
If this modification works in your environment as well, I believe it will be a powerful enhancement to our scraping process.

### CODE REVIEW

**Comment by TonicStark** [comment]
What an explanation! Thanks for the great work! I'm looking forward to testing the changes but from what I've seen, those looks like general changes that will pretty much work in all environment ;) I'll let you know as soon as possible the results (also given the fact that we live in different timezones, so it's a bit complicated with timing but is fun :D). Cheers!

**Comment by TonicStark** [comment]
Hi! I hope you're well. I wanted to bring to your attention that the box logo is set to release this Thursday, and we need to implement an auto-payment method for the checkout. I've attempted this before, but I believe the challenge lies in the complex generation of the form, making it difficult for the Playwright API to locate the input field elements. I would greatly appreciate it if you could explore potential solutions to this issue. You can see in the commit history that I've made multiple attempts to resolve it, but I'm still unsure about the best approach. Thank you for your assistance!

**Comment by kotaroyamazaki** [comment]
@TonicStark 
Didn't notice your comment.
Sorry about the last minute release date. I too am looking forward to the box logo sales.

I don't know if this will help you,I implemented the payment part in my environment as follows. It works on the Japanese site.
https://github.com/kotaroyamazaki/supreme-bot/blob/main/bot/bot.py

**Comment by TonicStark** [comment]
@kotaroyamazaki
No problem at all! I apologize for not mentioning you earlier, and I appreciate your understanding. This is one of my first collaborations on GitHub, and I'm still learning the ropes. I hope I'm doing well! I tested the changes you made, and they work perfectly, even in Europe. It seems I didn't commit enough in the past when working with the JavaScript evaluate method in Playwright or the iframe selector.

I want to express my gratitude for the significant improvements you've made to the project. It's incredible to see how far we've come from a project started during the COVID period. Now, we're discussing optimization and release dates, which is fantastic! :D

I understand you might have wanted to push the changes through a pull request to contribute officially. However, I've already implemented the changes myself. I hope this doesn't pose any inconvenience for you. Cheers!

**Comment by kotaroyamazaki** [comment]
@TonicStark 
> @kotaroyamazaki No problem at all! I apologize for not mentioning you earlier, and I appreciate your understanding. This is one of my first collaborations on GitHub, and I'm still learning the ropes. I hope I'm doing well! I tested the changes you made, and they work perfectly, even in Europe. It seems I didn't commit enough in the past when working with the JavaScript evaluate method in Playwright or the iframe selector.
> 
> I want to express my gratitude for the significant improvements you've made to the project. It's incredible to see how far we've come from a project started during the COVID period. Now, we're discussing optimization and release dates, which is fantastic! :D
> 
> I understand you might have wanted to push the changes through a pull request to contribute officially. However, I've already implemented the changes myself. I hope this doesn't pose any inconvenience for you. Cheers!

Don't worry about the contribution thing.
Your base implementation helped me a lot too.
It works perfectly in Japan (only reCAPTCHA is manual...)

One more piece of advice, when making multiple purchases, if you don't wait a little time after adding them to the cart, it will go to the next page before completing carting. I had to wait a bit.

https://github.com/kotaroyamazaki/supreme-bot/blob/d2c32b5d8ce9587640de1f6dc2485963c205cc9e/bot/bot.py#L133

I wish you all the best.

**Comment by TonicStark** [comment]
@kotaroyamazaki,
I've incorporated the changes you suggested. Thanks, they're highly effective! Currently enhancing UX – introduced a new navbar for improved category navigation, resolved graphical bugs related to items lacking sizing or selectable colors. Also working on enhancing form UI/UX, including the ability to save payment methods for future use. Not sure if you'll use it today for purchasing the box logo during the drop, but if you do, I'd appreciate your feedback on the experience! Cheers!

**Comment by kotaroyamazaki** [comment]
> @kotaroyamazaki, I've incorporated the changes you suggested. Thanks, they're highly effective! Currently enhancing UX – introduced a new navbar for improved category navigation, resolved graphical bugs related to items lacking sizing or selectable colors. Also working on enhancing form UI/UX, including the ability to save payment methods for future use. Not sure if you'll use it today for purchasing the box logo during the drop, but if you do, I'd appreciate your feedback on the experience! Cheers!

@TonicStark 

nice 👍🏻 
I'm looking forward to the update.
by the way, how was week 16 drop?

**Comment by TonicStark** [comment]
@kotaroyamazaki 
Here in Europe, it was tough. Items sold out very quickly, even the less hyped ones. I didn't try for the Box Logo, but after a few minutes, I checked, and it was almost all gone. I know in Japan, the drop is scheduled for 11 am, so it's coming up soon. If you try to purchase something, let me know! Cheers!

**Comment by kotaroyamazaki** [comment]
> @kotaroyamazaki Here in Europe, it was tough. Items sold out very quickly, even the less hyped ones. I didn't try for the Box Logo, but after a few minutes, I checked, and it was almost all gone. I know in Japan, the drop is scheduled for 11 am, so it's coming up soon. If you try to purchase something, let me know! Cheers!

@TonicStark 
omg, my bro
I don't know if you will like it, but I added the following features for quick purchase  in my code for Japan.
- Retry if the item doesn't exist
- launch timer
https://github.com/kotaroyamazaki/supreme-bot/commit/b816f568b3982c2e0cb35e0be848763ef3e5e73e

I hope this helps!


I'll try it tomorrow and plan to visit the actual store 😄 
I hope to bring you good news.

**Comment by kotaroyamazaki** [comment]
Online stores were wiped out.
I never made it past the point of waiting for the payment order. OMG

**Pull request merged**
